const SERVER_URL = 'http://localhost:3000/';
const SECOND = 1000;
const LOADER_COLOR = '#00BBEC';
const TEST_TOKEN ='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTg4MzY4MDYsImV4cCI6MTczMDM3MjgwNiwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImlkIjoiMyIsIm5hbWUiOiJxd2VyIn0.pjmSTW9jzE5nY1R71lcsCKYnaxtQuTj5Wh2VoNxH0zU';

export {SERVER_URL, SECOND, LOADER_COLOR, TEST_TOKEN};
